all:
	gcc ./src/2.task.c -Os -I../include -o 2task.exe
	gcc ./src/3.task.c -Os -I../include -o 3task.exe
	gcc ./src/4.task.c -Os -I../include -o 4task.exe
	gcc ./src/5.task.c -Os -I../include -o 5task.exe
	gcc ./src/6.task.c -Os -I../include -o 6task.exe
	gcc ./src/8.task.c -Os -I../include -o 8task.exe