win:
	gcc -fopenmp src/main.c src/parallelgeneration.c src/sequentialgeneration.c src/rng.c src/matrix.c -lmingw32 -Iinclude/ -o matrix_mult.exe
linux:
	gcc -fopenmp src/main.c src/parallelgeneration.c src/sequentialgeneration.c src/rng.c src/matrix.c -Iinclude/ -o matrix_mult